[package]
name = "Passman"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.22.0"
rand = { version = "0.8.5" }
csv = "1.2.2"
arboard = "3.2.1"
egui-notify = "0.8"